import {
  Image,
  FileImage,
  Film,
  Music,
  FileText,
  Code,
  ArrowRightLeft,
  Type,
  Binary,
  Hash,
  Fingerprint,
  Globe,
  Clock,
  Palette,
  Scissors,
  Crop,
  Layers,
  Sparkles,
  Wand2,
  FileJson,
  FileCode,
  Search,
  Shield,
  Merge,
  Split,
  Lock,
  Droplets,
  Minimize2,
  BarChart3,
  AudioWaveform,
  FileAudio,
  FileType,
  BadgeCheck,
  Diff,
  Repeat,
  Shrink,
  Ruler,
  ScanLine,
  Eye,
  HardDrive,
  Shuffle,
  ThermometerSun,
  Database,
  CreditCard,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export type ToolCategory =
  'Image' | 'Video' | 'Audio' | 'PDF & Documents' | 'Developer' | 'Utilities';

export interface ToolDef {
  id: string;
  name: string;
  category: ToolCategory;
  description: string;
  icon: LucideIcon;
  keywords: string[];
  fileTypes: string[];
  component: string;
}

export const CATEGORIES: ToolCategory[] = [
  'Image',
  'Video',
  'Audio',
  'PDF & Documents',
  'Developer',
  'Utilities',
];

export const TOOLS: ToolDef[] = [
  // ==========================================
  // 1. IMAGE
  // ==========================================
  {
    id: 'img-to-webp',
    name: 'Image → WebP',
    category: 'Image',
    description: 'Convert images to WebP format',
    icon: FileImage,
    keywords: ['make webp', 'convert webp', 'image webp', 'webp', 'save webp'],
    fileTypes: ['image/png', 'image/jpeg', 'image/jpg', 'image/gif', 'image/bmp', 'image/tiff'],
    component: 'ImgToWebp',
  },
  {
    id: 'img-to-avif',
    name: 'Image → AVIF',
    category: 'Image',
    description: 'Convert images to AVIF format',
    icon: FileImage,
    keywords: ['make avif', 'convert avif', 'image avif', 'avif'],
    fileTypes: ['image/png', 'image/jpeg', 'image/jpg', 'image/gif', 'image/webp'],
    component: 'ImgToAvif',
  },
  {
    id: 'img-to-png',
    name: 'Image → PNG',
    category: 'Image',
    description: 'Convert images to PNG format',
    icon: FileImage,
    keywords: ['make png', 'convert png', 'image png', 'png'],
    fileTypes: ['image/jpeg', 'image/jpg', 'image/gif', 'image/webp', 'image/avif', 'image/bmp'],
    component: 'ImgToPng',
  },
  {
    id: 'img-to-jpg',
    name: 'Image → JPG',
    category: 'Image',
    description: 'Convert images to JPEG format',
    icon: FileImage,
    keywords: ['make jpg', 'make jpeg', 'convert jpg', 'image jpg', 'jpeg'],
    fileTypes: ['image/png', 'image/webp', 'image/avif', 'image/bmp', 'image/gif'],
    component: 'ImgToJpg',
  },
  {
    id: 'svg-to-png',
    name: 'SVG → PNG',
    category: 'Image',
    description: 'Render SVG to PNG raster',
    icon: FileType,
    keywords: ['svg png', 'render svg', 'vector png', 'svg raster'],
    fileTypes: ['image/svg+xml'],
    component: 'SvgToPng',
  },
  {
    id: 'svg-to-webp',
    name: 'SVG → WebP',
    category: 'Image',
    description: 'Render SVG to WebP raster',
    icon: FileType,
    keywords: ['svg webp', 'render svg webp', 'vector webp'],
    fileTypes: ['image/svg+xml'],
    component: 'SvgToWebp',
  },
  {
    id: 'bulk-img-convert',
    name: 'Bulk Image Convert',
    category: 'Image',
    description: 'Convert multiple images at once',
    icon: Layers,
    keywords: ['batch images', 'bulk convert', 'multiple images', 'convert all'],
    fileTypes: [
      'image/png',
      'image/jpeg',
      'image/jpg',
      'image/webp',
      'image/gif',
      'image/bmp',
      'image/tiff',
    ],
    component: 'BulkImgConvert',
  },
  {
    id: 'img-compress',
    name: 'Image Compress',
    category: 'Image',
    description: 'Compress images with quality control',
    icon: Shrink,
    keywords: ['compress image', 'reduce size', 'optimize image', 'smaller image'],
    fileTypes: ['image/png', 'image/jpeg', 'image/jpg', 'image/webp'],
    component: 'ImgCompress',
  },
  {
    id: 'img-resize',
    name: 'Image Resize',
    category: 'Image',
    description: 'Resize images to exact dimensions',
    icon: Ruler,
    keywords: ['resize image', 'scale image', 'image dimensions', 'width height'],
    fileTypes: ['image/png', 'image/jpeg', 'image/jpg', 'image/webp', 'image/gif', 'image/bmp'],
    component: 'ImgResize',
  },
  {
    id: 'img-crop',
    name: 'Image Crop',
    category: 'Image',
    description: 'Crop images with visual selection',
    icon: Crop,
    keywords: ['crop image', 'trim image', 'cut image', 'image crop'],
    fileTypes: ['image/png', 'image/jpeg', 'image/jpg', 'image/webp', 'image/gif', 'image/bmp'],
    component: 'ImgCrop',
  },
  {
    id: 'img-metadata-clean',
    name: 'Metadata Clean',
    category: 'Image',
    description: 'Strip EXIF and metadata from images',
    icon: ScanLine,
    keywords: ['clean exif', 'remove metadata', 'strip metadata', 'privacy image'],
    fileTypes: ['image/jpeg', 'image/jpg', 'image/png', 'image/tiff'],
    component: 'ImgMetadataClean',
  },
  {
    id: 'svg-optimize',
    name: 'SVG Optimize',
    category: 'Image',
    description: 'Minimize and optimize SVG markup',
    icon: Wand2,
    keywords: ['optimize svg', 'minify svg', 'svg clean', 'svg compress'],
    fileTypes: ['image/svg+xml'],
    component: 'SvgOptimize',
  },
  {
    id: 'color-extract',
    name: 'Color Extract',
    category: 'Image',
    description: 'Extract dominant colors from images',
    icon: Palette,
    keywords: ['dominant colors', 'color palette', 'extract colors', 'image colors'],
    fileTypes: ['image/png', 'image/jpeg', 'image/jpg', 'image/webp', 'image/gif'],
    component: 'ColorExtract',
  },
  {
    id: 'palette-gen',
    name: 'Palette Gen',
    category: 'Image',
    description: 'Generate color palettes from images',
    icon: Sparkles,
    keywords: ['generate palette', 'color scheme', 'palette', 'swatch'],
    fileTypes: ['image/png', 'image/jpeg', 'image/jpg', 'image/webp'],
    component: 'PaletteGen',
  },
  {
    id: 'color-picker',
    name: 'Color Picker',
    category: 'Image',
    description: 'Interactive color picker with hex/RGB output',
    icon: Palette,
    keywords: ['color', 'picker', 'hex', 'rgb', 'wheel', 'select'],
    fileTypes: ['text/plain'],
    component: 'ColorPicker',
  },
  {
    id: 'palette-generator',
    name: 'Palette Generator',
    category: 'Image',
    description: 'Generate harmonious color palettes from a base color',
    icon: Palette,
    keywords: ['palette', 'generate', 'color', 'scheme', 'hsl', 'harmony'],
    fileTypes: ['text/plain'],
    component: 'PaletteGenerator',
  },
  {
    id: 'color-mixer',
    name: 'Color Mixer',
    category: 'Image',
    description: 'Mix two colors interactively with blend modes',
    icon: Shuffle,
    keywords: ['color', 'mix', 'blend', 'combine', 'mixer', 'merge'],
    fileTypes: ['text/plain'],
    component: 'ColorMixer',
  },
  {
    id: 'gradient-generator',
    name: 'Gradient Generator',
    category: 'Image',
    description: 'Generate CSS linear gradients and color stops',
    icon: Shuffle,
    keywords: ['gradient', 'css', 'linear', 'background', 'color', 'generate'],
    fileTypes: ['text/plain'],
    component: 'GradientGenerator',
  },
  {
    id: 'contrast-checker',
    name: 'Contrast Checker',
    category: 'Image',
    description: 'Check WCAG accessibility color contrast ratio',
    icon: Eye,
    keywords: ['contrast', 'wcag', 'accessibility', 'ratio', 'a11y', 'aa'],
    fileTypes: ['text/plain'],
    component: 'ContrastChecker',
  },
  {
    id: 'material-colors',
    name: 'Material Colors',
    category: 'Image',
    description: 'Material Design color palette reference swatch',
    icon: Palette,
    keywords: ['material', 'color', 'palette', 'md', 'design', 'ui'],
    fileTypes: ['text/plain'],
    component: 'MaterialColors',
  },
  {
    id: 'golden-ratio-palette',
    name: 'Golden Ratio Palette',
    category: 'Image',
    description: 'Generate harmonious colors using the golden ratio',
    icon: Shuffle,
    keywords: ['golden', 'ratio', 'palette', 'generate', 'harmony', 'color'],
    fileTypes: ['text/plain'],
    component: 'GoldenRatioPalette',
  },
  {
    id: 'hue-shift',
    name: 'Hue Shift',
    category: 'Image',
    description: 'Shift and rotate the hue of a color value',
    icon: Shuffle,
    keywords: ['hue', 'shift', 'color', 'rotate', 'hsl', 'transform'],
    fileTypes: ['text/plain'],
    component: 'HueShift',
  },
  {
    id: 'darken-lighten',
    name: 'Darken / Lighten',
    category: 'Image',
    description: 'Adjust color brightness, tints, and shades',
    icon: BarChart3,
    keywords: ['darken', 'lighten', 'brightness', 'adjust', 'color', 'tint'],
    fileTypes: ['text/plain'],
    component: 'DarkenLighten',
  },
  {
    id: 'tint-shade',
    name: 'Tint & Shade',
    category: 'Image',
    description: 'Generate systematic tints and shades of a color',
    icon: Shuffle,
    keywords: ['tint', 'shade', 'color', 'variation', 'palette', 'darken'],
    fileTypes: ['text/plain'],
    component: 'TintShade',
  },
  {
    id: 'color-blindness',
    name: 'Color Blindness Simulator',
    category: 'Image',
    description: 'Simulate protanopia, deuteranopia, and tritanopia vision',
    icon: Eye,
    keywords: ['color blind', 'simulate', 'protanopia', 'deuteranopia', 'tritanopia', 'a11y'],
    fileTypes: ['text/plain'],
    component: 'ColorBlindSimulator',
  },
  {
    id: 'color-generator',
    name: 'Color Generator',
    category: 'Image',
    description: 'Generate random curated color palettes',
    icon: Palette,
    keywords: ['color', 'generate', 'random', 'palette', 'hex'],
    fileTypes: ['text/plain'],
    component: 'ColorGenerator',
  },
  {
    id: 'hex-rgb',
    name: 'Hex to RGB',
    category: 'Image',
    description: 'Convert hex color code to RGB channel values',
    icon: Palette,
    keywords: ['hex', 'rgb', 'color', 'convert', 'hex to rgb'],
    fileTypes: ['text/plain'],
    component: 'HexToRgbTool',
  },
  {
    id: 'rgb-hex',
    name: 'RGB to Hex',
    category: 'Image',
    description: 'Convert RGB channel values to hex color code',
    icon: Palette,
    keywords: ['rgb', 'hex', 'color', 'convert', 'rgb to hex'],
    fileTypes: ['text/plain'],
    component: 'RgbToHexTool',
  },
  {
    id: 'rgb-hsl',
    name: 'RGB to HSL',
    category: 'Image',
    description: 'Convert RGB values to HSL color space',
    icon: Palette,
    keywords: ['rgb', 'hsl', 'convert', 'color', 'space', 'hsv'],
    fileTypes: ['text/plain'],
    component: 'RgbToHslTool',
  },
  {
    id: 'hsl-rgb',
    name: 'HSL to RGB',
    category: 'Image',
    description: 'Convert HSL values to RGB color space',
    icon: Palette,
    keywords: ['hsl', 'rgb', 'convert', 'color', 'space', 'hsv'],
    fileTypes: ['text/plain'],
    component: 'HslToRgbTool',
  },
  {
    id: 'color-temperature',
    name: 'Color Temperature',
    category: 'Image',
    description: 'Convert Kelvin color temperature to RGB values',
    icon: ThermometerSun,
    keywords: ['temperature', 'kelvin', 'rgb', 'white', 'warm', 'cool', 'convert'],
    fileTypes: ['text/plain'],
    component: 'ColorTemperature',
  },
  {
    id: 'base64-image',
    name: 'Base64 Image',
    category: 'Image',
    description: 'Convert images to Base64 data URI and back',
    icon: Binary,
    keywords: ['base64', 'encode', 'decode', 'image', 'binary', 'data uri'],
    fileTypes: ['text/plain', 'image/*'],
    component: 'Base64Image',
  },

  // ==========================================
  // 2. VIDEO
  // ==========================================
  {
    id: 'video-converter',
    name: 'Video Converter',
    category: 'Video',
    description: 'Convert between video formats',
    icon: Film,
    keywords: ['convert video', 'video format', 'mp4 mov', 'webm'],
    fileTypes: ['video/mp4', 'video/webm', 'video/quicktime', 'video/avi'],
    component: 'VideoConverter',
  },
  {
    id: 'video-to-hls',
    name: 'Video → HLS/M3U8',
    category: 'Video',
    description: 'Segment video for HLS streaming',
    icon: Film,
    keywords: ['hls', 'm3u8', 'segment video', 'streaming', 'video hls'],
    fileTypes: ['video/mp4', 'video/webm'],
    component: 'VideoToHls',
  },
  {
    id: 'video-to-gif',
    name: 'Video → GIF',
    category: 'Video',
    description: 'Extract frames to animated GIF',
    icon: Film,
    keywords: ['video gif', 'make gif', 'gif from video', 'extract gif'],
    fileTypes: ['video/mp4', 'video/webm', 'video/quicktime'],
    component: 'VideoToGif',
  },
  {
    id: 'gif-to-video',
    name: 'GIF → Video',
    category: 'Video',
    description: 'Convert GIF to video format',
    icon: Film,
    keywords: ['gif video', 'convert gif', 'gif to mp4', 'gif to webm'],
    fileTypes: ['image/gif'],
    component: 'GifToVideo',
  },
  {
    id: 'video-to-audio',
    name: 'Video → Audio',
    category: 'Video',
    description: 'Extract audio track from video',
    icon: AudioWaveform,
    keywords: ['extract audio', 'audio from video', 'strip audio', 'video audio'],
    fileTypes: ['video/mp4', 'video/webm', 'video/quicktime'],
    component: 'VideoToAudio',
  },
  {
    id: 'video-compress',
    name: 'Video Compress',
    category: 'Video',
    description: 'Compress video with bitrate control',
    icon: Shrink,
    keywords: ['compress video', 'reduce video size', 'video bitrate', 'smaller video'],
    fileTypes: ['video/mp4', 'video/webm', 'video/quicktime'],
    component: 'VideoCompress',
  },
  {
    id: 'video-trim',
    name: 'Video Trim',
    category: 'Video',
    description: 'Trim video to specific range',
    icon: Scissors,
    keywords: ['trim video', 'cut video', 'video start end', 'video slice'],
    fileTypes: ['video/mp4', 'video/webm', 'video/quicktime', 'video/avi'],
    component: 'VideoTrim',
  },
  {
    id: 'frame-extract',
    name: 'Frame Extract',
    category: 'Video',
    description: 'Extract single frames from video',
    icon: Image,
    keywords: ['frame grab', 'video frame', 'screenshot video', 'extract frame'],
    fileTypes: ['video/mp4', 'video/webm', 'video/quicktime'],
    component: 'FrameExtract',
  },
  {
    id: 'video-thumbnails',
    name: 'Video Thumbnails',
    category: 'Video',
    description: 'Generate thumbnail grid from video',
    icon: Layers,
    keywords: ['thumbnails', 'video poster', 'grid', 'video preview'],
    fileTypes: ['video/mp4', 'video/webm', 'video/quicktime'],
    component: 'VideoThumbnails',
  },
  {
    id: 'video-metadata',
    name: 'Video Metadata',
    category: 'Video',
    description: 'Inspect codec, resolution, and metadata info',
    icon: BadgeCheck,
    keywords: ['video info', 'codec', 'metadata', 'video inspect', 'video details'],
    fileTypes: ['video/mp4', 'video/webm', 'video/quicktime', 'video/avi', 'video/mkv'],
    component: 'VideoMetadata',
  },

  // ==========================================
  // 3. AUDIO
  // ==========================================
  {
    id: 'audio-converter',
    name: 'Audio Converter',
    category: 'Audio',
    description: 'Convert between audio formats',
    icon: Music,
    keywords: ['convert audio', 'audio format', 'mp3 wav', 'ogg'],
    fileTypes: ['audio/mpeg', 'audio/wav', 'audio/ogg', 'audio/aac', 'audio/flac'],
    component: 'AudioConverter',
  },
  {
    id: 'audio-compress',
    name: 'Audio Compress',
    category: 'Audio',
    description: 'Compress audio with quality settings',
    icon: Shrink,
    keywords: ['compress audio', 'reduce audio', 'audio bitrate', 'smaller audio'],
    fileTypes: ['audio/mpeg', 'audio/wav', 'audio/ogg', 'audio/aac', 'audio/flac'],
    component: 'AudioCompress',
  },
  {
    id: 'audio-trim',
    name: 'Audio Trim',
    category: 'Audio',
    description: 'Trim audio to specific start and end points',
    icon: Scissors,
    keywords: ['trim audio', 'cut audio', 'audio start end', 'audio slice'],
    fileTypes: ['audio/mpeg', 'audio/wav', 'audio/ogg', 'audio/aac', 'audio/flac', 'audio/mp4'],
    component: 'AudioTrim',
  },
  {
    id: 'id3-edit',
    name: 'ID3 Edit',
    category: 'Audio',
    description: 'Edit MP3 metadata tags, album, artist, title',
    icon: FileAudio,
    keywords: ['id3 tag', 'mp3 metadata', 'audio title', 'artist album'],
    fileTypes: ['audio/mpeg'],
    component: 'Id3Edit',
  },
  {
    id: 'waveform-gen',
    name: 'Waveform Gen',
    category: 'Audio',
    description: 'Generate audio waveform visualization graph',
    icon: BarChart3,
    keywords: ['waveform', 'audio visual', 'sound wave', 'audio graph'],
    fileTypes: ['audio/mpeg', 'audio/wav', 'audio/ogg', 'audio/aac', 'audio/flac'],
    component: 'WaveformGen',
  },

  // ==========================================
  // 4. PDF & DOCUMENTS
  // ==========================================
  {
    id: 'pdf-to-images',
    name: 'PDF → Images',
    category: 'PDF & Documents',
    description: 'Render PDF pages as images',
    icon: FileText,
    keywords: ['pdf images', 'pdf to png', 'pdf to jpg', 'render pdf'],
    fileTypes: ['application/pdf'],
    component: 'PdfToImages',
  },
  {
    id: 'images-to-pdf',
    name: 'Images → PDF',
    category: 'PDF & Documents',
    description: 'Combine images into PDF document',
    icon: FileText,
    keywords: ['images pdf', 'make pdf', 'jpg to pdf', 'png to pdf', 'photo pdf'],
    fileTypes: ['image/png', 'image/jpeg', 'image/jpg', 'image/webp'],
    component: 'ImagesToPdf',
  },
  {
    id: 'markdown-html',
    name: 'Markdown to HTML',
    category: 'PDF & Documents',
    description: 'Convert Markdown to HTML markup',
    icon: FileText,
    keywords: ['markdown', 'html', 'md', 'render', 'convert', 'markup'],
    fileTypes: ['text/plain', 'text/markdown'],
    component: 'MarkdownToHtml',
  },
  {
    id: 'pdf-merge',
    name: 'PDF Merge',
    category: 'PDF & Documents',
    description: 'Combine multiple PDFs into one document',
    icon: Merge,
    keywords: ['merge pdf', 'combine pdf', 'join pdf', 'pdf together'],
    fileTypes: ['application/pdf'],
    component: 'PdfMerge',
  },
  {
    id: 'pdf-split',
    name: 'PDF Split',
    category: 'PDF & Documents',
    description: 'Split PDF into separate page files',
    icon: Split,
    keywords: ['split pdf', 'separate pdf', 'pdf pages', 'extract pages'],
    fileTypes: ['application/pdf'],
    component: 'PdfSplit',
  },
  {
    id: 'pdf-compress',
    name: 'PDF Compress',
    category: 'PDF & Documents',
    description: 'Reduce PDF file size and optimize assets',
    icon: Shrink,
    keywords: ['compress pdf', 'reduce pdf', 'smaller pdf', 'optimize pdf'],
    fileTypes: ['application/pdf'],
    component: 'PdfCompress',
  },
  {
    id: 'pdf-extract-reorder',
    name: 'PDF Extract / Reorder',
    category: 'PDF & Documents',
    description: 'Extract and reorder PDF pages visually',
    icon: Repeat,
    keywords: ['reorder pdf', 'pdf pages', 'rearrange pdf', 'pdf extract'],
    fileTypes: ['application/pdf'],
    component: 'PdfExtractReorder',
  },
  {
    id: 'pdf-metadata',
    name: 'PDF Metadata',
    category: 'PDF & Documents',
    description: 'View and edit PDF title, author, and info',
    icon: BadgeCheck,
    keywords: ['pdf info', 'pdf metadata', 'pdf properties', 'pdf title'],
    fileTypes: ['application/pdf'],
    component: 'PdfMetadata',
  },
  {
    id: 'pdf-password',
    name: 'PDF Password',
    category: 'PDF & Documents',
    description: 'Protect or unlock PDF documents',
    icon: Lock,
    keywords: ['pdf password', 'encrypt pdf', 'decrypt pdf', 'pdf lock', 'pdf unlock'],
    fileTypes: ['application/pdf'],
    component: 'PdfPassword',
  },
  {
    id: 'pdf-watermark',
    name: 'PDF Watermark',
    category: 'PDF & Documents',
    description: 'Add custom text or image watermarks to PDF',
    icon: Droplets,
    keywords: ['watermark pdf', 'pdf stamp', 'pdf overlay', 'pdf mark'],
    fileTypes: ['application/pdf'],
    component: 'PdfWatermark',
  },

  // ==========================================
  // 5. DEVELOPER
  // ==========================================
  {
    id: 'json-format',
    name: 'JSON Format',
    category: 'Developer',
    description: 'Format, validate, and prettify JSON data',
    icon: FileJson,
    keywords: ['json format', 'prettify json', 'json validate', 'json lint'],
    fileTypes: ['application/json', 'text/plain'],
    component: 'JsonFormat',
  },
  {
    id: 'json-yaml',
    name: 'JSON ↔ YAML',
    category: 'Developer',
    description: 'Convert between JSON and YAML',
    icon: ArrowRightLeft,
    keywords: ['json yaml', 'yaml json', 'convert json', 'convert yaml'],
    fileTypes: ['application/json', 'text/yaml', 'application/x-yaml'],
    component: 'JsonYaml',
  },
  {
    id: 'json-csv',
    name: 'JSON ↔ CSV',
    category: 'Developer',
    description: 'Convert between JSON and CSV',
    icon: ArrowRightLeft,
    keywords: ['json csv', 'csv json', 'convert csv', 'table json'],
    fileTypes: ['application/json', 'text/csv'],
    component: 'JsonCsv',
  },
  {
    id: 'xml-json',
    name: 'XML to JSON',
    category: 'Developer',
    description: 'Convert XML document to JSON format',
    icon: Code,
    keywords: ['xml', 'json', 'convert', 'parse', 'x2j'],
    fileTypes: ['text/plain', 'application/xml'],
    component: 'XmlToJson',
  },
  {
    id: 'json-xml',
    name: 'JSON to XML',
    category: 'Developer',
    description: 'Convert JSON format to XML document',
    icon: Code,
    keywords: ['json', 'xml', 'convert', 'generate', 'j2x'],
    fileTypes: ['application/json', 'text/plain'],
    component: 'JsonToXml',
  },
  {
    id: 'binary-converter',
    name: 'Binary Converter',
    category: 'Developer',
    description: 'Convert between binary, decimal, and hexadecimal bases',
    icon: Binary,
    keywords: ['binary', 'decimal', 'hex', 'convert', 'number base', 'radix'],
    fileTypes: ['text/plain'],
    component: 'BinaryConverter',
  },
  {
    id: 'text-case',
    name: 'Text Case Converter',
    category: 'Developer',
    description: 'Convert text case between UPPER, lower, Title, Camel, Snake',
    icon: Type,
    keywords: ['text', 'case', 'upper', 'lower', 'title', 'convert', 'camel', 'snake'],
    fileTypes: ['text/plain'],
    component: 'TextCase',
  },
  {
    id: 'morse-code',
    name: 'Morse Code Translator',
    category: 'Developer',
    description: 'Translate between text and Morse code telegraph audio',
    icon: Type,
    keywords: ['morse', 'morse code', 'translate', 'telegraph', 'code', 'convert'],
    fileTypes: ['text/plain'],
    component: 'MorseCode',
  },
  {
    id: 'base64',
    name: 'Base64',
    category: 'Developer',
    description: 'Encode and decode standard Base64 strings',
    icon: Binary,
    keywords: ['base64 encode', 'base64 decode', 'encode', 'decode', 'convert'],
    fileTypes: ['text/plain'],
    component: 'Base64',
  },
  {
    id: 'base32',
    name: 'Base32 Encoder',
    category: 'Developer',
    description: 'Encode and decode RFC 4648 Base32 strings',
    icon: Binary,
    keywords: ['base32', 'encode', 'decode', 'rfc 4648', 'binary', 'convert'],
    fileTypes: ['text/plain'],
    component: 'Base32Tool',
  },
  {
    id: 'url-encode',
    name: 'URL Encode',
    category: 'Developer',
    description: 'Encode and decode URL percent-encoded strings',
    icon: Globe,
    keywords: ['url encode', 'url decode', 'percent encode', 'uri encode', 'convert'],
    fileTypes: ['text/plain'],
    component: 'UrlEncode',
  },
  {
    id: 'unix-timestamp',
    name: 'Unix / Timestamp',
    category: 'Developer',
    description: 'Convert between Unix timestamps and dates',
    icon: Clock,
    keywords: ['unix timestamp', 'epoch', 'date convert', 'timestamp'],
    fileTypes: ['text/plain'],
    component: 'UnixTimestamp',
  },
  {
    id: 'jwt-inspect',
    name: 'JWT Inspect',
    category: 'Developer',
    description: 'Decode and inspect JSON Web Tokens',
    icon: Shield,
    keywords: ['decode jwt', 'jwt token', 'inspect jwt', 'json web token'],
    fileTypes: ['text/plain'],
    component: 'JwtInspect',
  },
  {
    id: 'hash-gen',
    name: 'Hash Gen',
    category: 'Developer',
    description: 'Generate SHA-256, SHA-512, MD5 hashes',
    icon: Hash,
    keywords: ['sha256', 'md5', 'hash', 'checksum', 'generate hash'],
    fileTypes: ['text/plain'],
    component: 'HashGen',
  },
  {
    id: 'checksum',
    name: 'Checksum Generator',
    category: 'Developer',
    description: 'Generate cryptographic file and text checksums',
    icon: Hash,
    keywords: ['checksum', 'sha256', 'hash', 'verify', 'integrity', 'digest'],
    fileTypes: ['text/plain'],
    component: 'Checksum',
  },
  {
    id: 'salt-generator',
    name: 'Salt Generator',
    category: 'Developer',
    description: 'Generate random cryptographic salts',
    icon: Shield,
    keywords: ['salt', 'crypto', 'security', 'generate', 'hashing'],
    fileTypes: ['text/plain'],
    component: 'SaltGenerator',
  },
  {
    id: 'hex-generator',
    name: 'Hex Generator',
    category: 'Developer',
    description: 'Generate cryptographically random hex strings',
    icon: Binary,
    keywords: ['hex', 'random', 'generate', 'string', 'hexadecimal'],
    fileTypes: ['text/plain'],
    component: 'HexGenerator',
  },
  {
    id: 'key-pair-generator',
    name: 'Key Pair Generator',
    category: 'Developer',
    description: 'Generate RSA public and private key pairs',
    icon: Shield,
    keywords: ['rsa', 'key', 'pair', 'crypto', 'public private'],
    fileTypes: ['text/plain'],
    component: 'KeyPairGenerator',
  },
  {
    id: 'otp-generator',
    name: 'OTP Generator',
    category: 'Developer',
    description: 'Generate TOTP/HOTP one-time passwords',
    icon: Clock,
    keywords: ['otp', 'one-time', 'password', 'totp', '2fa'],
    fileTypes: ['text/plain'],
    component: 'OTPGenerator',
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    category: 'Developer',
    description: 'Test regular expressions with test samples and flags',
    icon: Search,
    keywords: ['regex', 'regular expression', 'pattern match', 'test regex'],
    fileTypes: ['text/plain'],
    component: 'RegexTester',
  },
  {
    id: 'regex-replace',
    name: 'Regex Replace',
    category: 'Developer',
    description: 'Find and replace text using regular expressions',
    icon: Search,
    keywords: ['regex', 'replace', 'find replace', 'pattern', 'search'],
    fileTypes: ['text/plain'],
    component: 'RegexReplace',
  },
  {
    id: 'diff-checker',
    name: 'Diff Checker',
    category: 'Developer',
    description: 'Compare two texts side-by-side with diff highlighting',
    icon: Diff,
    keywords: ['diff', 'compare text', 'difference', 'text compare'],
    fileTypes: ['text/plain'],
    component: 'DiffChecker',
  },
  {
    id: 'markdown-preview',
    name: 'Markdown Preview',
    category: 'Developer',
    description: 'Live Markdown preview with rendered styling',
    icon: FileCode,
    keywords: ['markdown preview', 'md render', 'markdown', 'md preview'],
    fileTypes: ['text/markdown', 'text/plain'],
    component: 'MarkdownPreview',
  },
  {
    id: 'code-minify',
    name: 'Code Minify',
    category: 'Developer',
    description: 'Minify JavaScript, CSS, and HTML code',
    icon: Minimize2,
    keywords: ['minify', 'uglify', 'compress code', 'js minify', 'css minify'],
    fileTypes: ['text/plain', 'application/javascript', 'text/css', 'text/html'],
    component: 'CodeMinify',
  },
  {
    id: 'html-minifier',
    name: 'HTML Minifier',
    category: 'Developer',
    description: 'Minify HTML by stripping comments and spaces',
    icon: FileText,
    keywords: ['html', 'minify', 'compress', 'clean', 'optimize'],
    fileTypes: ['text/plain'],
    component: 'HtmlMinifier',
  },
  {
    id: 'css-minifier',
    name: 'CSS Minifier',
    category: 'Developer',
    description: 'Minify CSS stylesheets',
    icon: FileText,
    keywords: ['css', 'minify', 'compress', 'clean', 'optimize'],
    fileTypes: ['text/plain'],
    component: 'CssMinifier',
  },
  {
    id: 'js-minifier',
    name: 'JS Minifier',
    category: 'Developer',
    description: 'Minify JavaScript source files',
    icon: Code,
    keywords: ['js', 'javascript', 'minify', 'uglify', 'compress'],
    fileTypes: ['text/plain'],
    component: 'JsMinifier',
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    category: 'Developer',
    description: 'Format and beautify SQL queries',
    icon: Database,
    keywords: ['sql', 'format', 'beautify', 'query', 'database'],
    fileTypes: ['text/plain'],
    component: 'SqlFormatter',
  },
  {
    id: 'jsonpath-tester',
    name: 'JSONPath Tester',
    category: 'Developer',
    description: 'Test JSONPath query expressions against JSON objects',
    icon: Search,
    keywords: ['jsonpath', 'json path', 'query', 'test', 'xpath'],
    fileTypes: ['text/plain'],
    component: 'JsonPathTester',
  },
  {
    id: 'http-headers',
    name: 'HTTP Headers Parser',
    category: 'Developer',
    description: 'Parse and inspect HTTP request/response headers',
    icon: Globe,
    keywords: ['http', 'headers', 'parse', 'request', 'response', 'web'],
    fileTypes: ['text/plain'],
    component: 'HttpHeadersParser',
  },
  {
    id: 'user-agent-parser',
    name: 'User Agent Parser',
    category: 'Developer',
    description: 'Parse browser user agent string details',
    icon: Globe,
    keywords: ['user agent', 'browser', 'ua', 'parse', 'detect', 'web'],
    fileTypes: ['text/plain'],
    component: 'UserAgentParser',
  },
  {
    id: 'url-parser',
    name: 'URL Parser',
    category: 'Developer',
    description: 'Parse and inspect URL components and query params',
    icon: Globe,
    keywords: ['url', 'parse', 'uri', 'components', 'protocol', 'query'],
    fileTypes: ['text/plain'],
    component: 'UrlParser',
  },
  {
    id: 'url-slug',
    name: 'URL Slug Generator',
    category: 'Developer',
    description: 'Generate clean URL-friendly slugs from title text',
    icon: Globe,
    keywords: ['slug', 'url', 'seo', 'permalink', 'sanitize', 'clean'],
    fileTypes: ['text/plain'],
    component: 'UrlSlug',
  },
  {
    id: 'html-escape',
    name: 'HTML Escape',
    category: 'Developer',
    description: 'Escape or unescape HTML entities and special characters',
    icon: FileText,
    keywords: ['html', 'escape', 'unescape', 'entities', 'encode', 'decode'],
    fileTypes: ['text/plain'],
    component: 'HtmlEscape',
  },
  {
    id: 'cron-generator',
    name: 'Cron Expression Generator',
    category: 'Developer',
    description: 'Generate and validate cron schedule expressions',
    icon: Clock,
    keywords: ['cron', 'schedule', 'cron expression', 'timer', 'crontab'],
    fileTypes: ['text/plain'],
    component: 'CronGenerator',
  },
  {
    id: 'env-generator',
    name: 'Env File Generator',
    category: 'Developer',
    description: 'Generate .env template environment variable files',
    icon: FileText,
    keywords: ['env', 'environment', 'config', 'dotenv', 'variables'],
    fileTypes: ['text/plain'],
    component: 'EnvFileGenerator',
  },
  {
    id: 'tailwind-colors',
    name: 'Tailwind Colors',
    category: 'Developer',
    description: 'Tailwind CSS color classes and hex values reference',
    icon: Layers,
    keywords: ['tailwind', 'color', 'palette', 'css', 'reference', 'ui'],
    fileTypes: ['text/plain'],
    component: 'TailwindColors',
  },
  {
    id: 'character-map',
    name: 'Character Map',
    category: 'Developer',
    description: 'Look up Unicode codepoint info for characters',
    icon: Search,
    keywords: ['character', 'unicode', 'map', 'codepoint', 'hex', 'char'],
    fileTypes: ['text/plain'],
    component: 'CharMap',
  },
  {
    id: 'text-counter',
    name: 'Text Counter',
    category: 'Developer',
    description: 'Count characters, words, sentences, and lines',
    icon: FileText,
    keywords: ['count', 'text', 'characters', 'words', 'lines', 'stats'],
    fileTypes: ['text/plain'],
    component: 'TextCounter',
  },
  {
    id: 'line-counter',
    name: 'Line Counter',
    category: 'Developer',
    description: 'Count and analyze source code lines',
    icon: FileText,
    keywords: ['line', 'count', 'counter', 'lines', 'total', 'analyze'],
    fileTypes: ['text/plain'],
    component: 'LineCounter',
  },
  {
    id: 'whitespace-remover',
    name: 'Whitespace Remover',
    category: 'Developer',
    description: 'Remove trailing spaces and normalize text whitespace',
    icon: FileText,
    keywords: ['whitespace', 'trim', 'clean', 'normalize', 'spaces', 'tabs'],
    fileTypes: ['text/plain'],
    component: 'WhitespaceRemover',
  },
  {
    id: 'text-formatter',
    name: 'Text Formatter',
    category: 'Developer',
    description: 'Format text to fixed column width wrapping',
    icon: FileText,
    keywords: ['format', 'text', 'column', 'wrap', 'width', 'align'],
    fileTypes: ['text/plain'],
    component: 'TextFormatter',
  },
  {
    id: 'text-reverse',
    name: 'Text Reverse',
    category: 'Developer',
    description: 'Reverse text character-by-character or word-by-word',
    icon: Type,
    keywords: ['reverse', 'text', 'invert', 'backwards', 'flip', 'string'],
    fileTypes: ['text/plain'],
    component: 'TextReverse',
  },
  {
    id: 'leet-speak',
    name: 'Leet Speak',
    category: 'Developer',
    description: 'Convert text to 1337 leetspeak dialect',
    icon: Type,
    keywords: ['leet', 'speak', '1337', 'hack', 'convert', 'text'],
    fileTypes: ['text/plain'],
    component: 'LeetSpeak',
  },
  {
    id: 'text-to-ascii',
    name: 'Text to ASCII Art',
    category: 'Developer',
    description: 'Convert text to ASCII banner font typography',
    icon: Type,
    keywords: ['ascii', 'art', 'text', 'banner', 'figlet', 'design'],
    fileTypes: ['text/plain'],
    component: 'TextToAscii',
  },
  {
    id: 'caesar-cipher',
    name: 'Caesar Cipher',
    category: 'Developer',
    description: 'Encrypt and decrypt text using Caesar shift cipher',
    icon: Shield,
    keywords: ['caesar', 'cipher', 'encrypt', 'decrypt', 'shift', 'crypto'],
    fileTypes: ['text/plain'],
    component: 'CaesarCipher',
  },
  {
    id: 'text-encrypt',
    name: 'Text Encrypt',
    category: 'Developer',
    description: 'Encrypt/decrypt text with symmetric XOR key cipher',
    icon: Shield,
    keywords: ['encrypt', 'decrypt', 'xor', 'cipher', 'password', 'text'],
    fileTypes: ['text/plain'],
    component: 'TextEncrypt',
  },
  {
    id: 'phone-formatter',
    name: 'Phone Formatter',
    category: 'Developer',
    description: 'Format phone numbers into standardized regional formats',
    icon: Globe,
    keywords: ['phone', 'format', 'number', 'formatter', 'us', 'tel'],
    fileTypes: ['text/plain'],
    component: 'PhoneNumberFormat',
  },
  {
    id: 'credit-card-format',
    name: 'Credit Card Formatter',
    category: 'Developer',
    description: 'Format credit card numbers into separated quad groups',
    icon: CreditCard,
    keywords: ['credit card', 'format', 'card', 'number', 'groups'],
    fileTypes: ['text/plain'],
    component: 'CreditCardFormat',
  },
  {
    id: 'password-strength',
    name: 'Password Strength Checker',
    category: 'Developer',
    description: 'Analyze password entropy and estimate crack time',
    icon: Shield,
    keywords: ['password', 'strength', 'security', 'weak', 'strong', 'crack'],
    fileTypes: ['text/plain'],
    component: 'PasswordStrength',
  },

  // ==========================================
  // 6. UTILITIES
  // ==========================================
  {
    id: 'currency-converter',
    name: 'Currency Converter',
    category: 'Utilities',
    description: 'Convert between major world currencies',
    icon: Globe,
    keywords: ['currency', 'money', 'exchange', 'convert', 'forex'],
    fileTypes: ['text/plain'],
    component: 'CurrencyConverter',
  },
  {
    id: 'timezone-converter',
    name: 'Timezone Converter',
    category: 'Utilities',
    description: 'Convert UTC time to different global timezones',
    icon: Clock,
    keywords: ['timezone', 'time', 'convert', 'utc', 'offset', 'zone'],
    fileTypes: ['text/plain'],
    component: 'TimeZoneConverter',
  },
  {
    id: 'file-size-converter',
    name: 'File Size Converter',
    category: 'Utilities',
    description: 'Convert bytes to human-readable units (KB, MB, GB, TB)',
    icon: HardDrive,
    keywords: ['file size', 'bytes', 'kb', 'mb', 'gb', 'convert', 'units'],
    fileTypes: ['text/plain'],
    component: 'FileSizeConverter',
  },
  {
    id: 'oven-temperature',
    name: 'Oven Temperature',
    category: 'Utilities',
    description: 'Convert oven temperatures between Fahrenheit, Celsius, and Gas Mark',
    icon: ThermometerSun,
    keywords: ['oven', 'temperature', 'fahrenheit', 'celsius', 'baking', 'cooking'],
    fileTypes: ['text/plain'],
    component: 'OvenTemp',
  },
  {
    id: 'clothing-size',
    name: 'Clothing Size Converter',
    category: 'Utilities',
    description: 'Convert clothing sizes across US, EU, and UK systems',
    icon: Layers,
    keywords: ['clothing', 'size', 'convert', 'us', 'eu', 'uk', 'shirt', 'dress'],
    fileTypes: ['text/plain'],
    component: 'ClothingSize',
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    category: 'Utilities',
    description: 'Generate strong, customizable random passwords',
    icon: Shield,
    keywords: ['password', 'generate', 'random', 'security', 'strong'],
    fileTypes: ['text/plain'],
    component: 'PasswordGenerator',
  },
  {
    id: 'secure-token',
    name: 'Secure Token',
    category: 'Utilities',
    description: 'Generate cryptographically secure random API tokens',
    icon: Shield,
    keywords: ['token', 'secure', 'crypto', 'random', 'api key'],
    fileTypes: ['text/plain'],
    component: 'SecureToken',
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    category: 'Utilities',
    description: 'Generate standard UUID v4 and v1 identifiers',
    icon: Fingerprint,
    keywords: ['uuid', 'guid', 'generate', 'unique', 'id'],
    fileTypes: ['text/plain'],
    component: 'UuidGenerator',
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum',
    category: 'Utilities',
    description: 'Generate placeholder dummy text paragraphs and words',
    icon: FileText,
    keywords: ['lorem', 'ipsum', 'placeholder', 'text', 'dummy'],
    fileTypes: ['text/plain'],
    component: 'LoremIpsum',
  },
  {
    id: 'random-number',
    name: 'Random Number',
    category: 'Utilities',
    description: 'Generate random numbers within a min/max range',
    icon: BarChart3,
    keywords: ['random', 'number', 'rng', 'dice', 'chance'],
    fileTypes: ['text/plain'],
    component: 'RandomNumber',
  },
  {
    id: 'dice-roller',
    name: 'Dice Roller',
    category: 'Utilities',
    description: 'Roll dice with NdM notation (e.g. 2d6, 1d20)',
    icon: Layers,
    keywords: ['dice', 'roll', 'random', 'game', 'd20'],
    fileTypes: ['text/plain'],
    component: 'DiceRoller',
  },
  {
    id: 'random-picker',
    name: 'Random Picker',
    category: 'Utilities',
    description: 'Pick a random winner from a list of custom choices',
    icon: Shuffle,
    keywords: ['random', 'pick', 'choice', 'selector', 'wheel', 'draw'],
    fileTypes: ['text/plain'],
    component: 'RandomPicker',
  },
  {
    id: 'name-generator',
    name: 'Name Generator',
    category: 'Utilities',
    description: 'Generate fantasy, cyberpunk, or tech project names',
    icon: Type,
    keywords: ['name', 'generate', 'fantasy', 'random', 'character'],
    fileTypes: ['text/plain'],
    component: 'NameGenerator',
  },
  {
    id: 'mac-address-generator',
    name: 'MAC Address Gen',
    category: 'Utilities',
    description: 'Generate random MAC hardware addresses',
    icon: Globe,
    keywords: ['mac', 'address', 'network', 'ethernet', 'nic'],
    fileTypes: ['text/plain'],
    component: 'MACGenerator',
  },
  {
    id: 'ipv4-generator',
    name: 'IPv4 Generator',
    category: 'Utilities',
    description: 'Generate random IPv4 network addresses',
    icon: Globe,
    keywords: ['ip', 'ipv4', 'address', 'network', 'random'],
    fileTypes: ['text/plain'],
    component: 'IPv4Generator',
  },
  {
    id: 'credit-card-generator',
    name: 'Credit Card Gen',
    category: 'Utilities',
    description: 'Generate valid test credit card numbers for staging',
    icon: CreditCard,
    keywords: ['credit', 'card', 'generate', 'test', 'fake'],
    fileTypes: ['text/plain'],
    component: 'CreditCardGenerator',
  },
  {
    id: 'serial-number',
    name: 'Serial Number Gen',
    category: 'Utilities',
    description: 'Generate formatted serial license keys',
    icon: Hash,
    keywords: ['serial', 'number', 'generate', 'license', 'code'],
    fileTypes: ['text/plain'],
    component: 'SerialNumber',
  },
  {
    id: 'barcode-generator',
    name: 'Barcode Generator',
    category: 'Utilities',
    description: 'Generate EAN-13 barcode numbers and checksums',
    icon: ScanLine,
    keywords: ['barcode', 'ean', 'generate', 'product', 'code'],
    fileTypes: ['text/plain'],
    component: 'BarCode',
  },
  {
    id: 'lottery-generator',
    name: 'Lottery Generator',
    category: 'Utilities',
    description: 'Generate random lottery and lucky number picks',
    icon: Layers,
    keywords: ['lottery', 'numbers', 'random', 'bingo', 'gamble'],
    fileTypes: ['text/plain'],
    component: 'LotteryGenerator',
  },
];

export function findToolById(id: string): ToolDef | undefined {
  return TOOLS.find((t) => t.id === id);
}

export function findToolsByFileType(fileType: string): ToolDef[] {
  return TOOLS.filter((t) => {
    if (t.fileTypes.includes(fileType)) return true;
    if (fileType.startsWith('image/') && t.fileTypes.includes('image/*')) return true;
    if (fileType.startsWith('video/') && t.fileTypes.includes('video/*')) return true;
    if (fileType.startsWith('audio/') && t.fileTypes.includes('audio/*')) return true;
    return false;
  });
}

export function searchTools(query: string): ToolDef[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return TOOLS.filter((t) => {
    if (t.name.toLowerCase().includes(q)) return true;
    if (t.description.toLowerCase().includes(q)) return true;
    if (t.category.toLowerCase().includes(q)) return true;
    if (t.keywords.some((k) => k.includes(q))) return true;
    return false;
  }).sort((a, b) => {
    const aName = a.name.toLowerCase().includes(q)
      ? 2
      : a.keywords.some((k) => k.includes(q))
        ? 1
        : 0;
    const bName = b.name.toLowerCase().includes(q)
      ? 2
      : b.keywords.some((k) => k.includes(q))
        ? 1
        : 0;
    return bName - aName;
  });
}

export function getToolsByCategory(category: ToolCategory): ToolDef[] {
  return TOOLS.filter((t) => t.category === category);
}
