apiVersion: v1
kind: Secret
metadata:
  name: nammu-os-secrets
  namespace: nammu-os
type: Opaque
stringData:
  DATABASE_URL: 'postgresql://postgres:nammu_secret_password@postgres-service:5432/nammu_os'
  REDIS_URL: 'redis://redis-service:6379'
  AUTH_SECRET: 'nammu-enterprise-production-auth-secret-key-999'
