import type { PlatformCapabilities, PlatformRuntime } from './contracts';
import { getPlatformRuntime } from './runtime';
import { tauriPlatformCapabilities } from './tauri';
import { webPlatformCapabilities } from './web';

const capabilitiesByRuntime: Readonly<Record<PlatformRuntime, PlatformCapabilities>> =
  Object.freeze({
    web: webPlatformCapabilities,
    tauri: tauriPlatformCapabilities,
  });

export function getPlatformCapabilities(
  runtime: PlatformRuntime = getPlatformRuntime(),
): PlatformCapabilities {
  return capabilitiesByRuntime[runtime];
}

export { detectPlatformRuntime, getPlatformRuntime } from './runtime';
export type {
  CapabilityResult,
  DirectoryMeasurementDiagnostics,
  DirectoryMeasurementSnapshot,
  DirectoryMeasurementState,
  FilesystemError,
  FilesystemErrorCode,
  FilesystemResult,
  NativeArchiveConflictStrategy,
  NativeArchiveDiagnostics,
  NativeArchiveEntry,
  NativeArchiveEntryKind,
  NativeArchiveFailure,
  NativeArchiveListing,
  NativeArchiveOperationSnapshot,
  NativeArchiveOperationState,
  NativeArchiveOperationType,
  NativeArchiveSummary,
  NativeDirectoryListing,
  NativeDirectoryWatchDiagnostics,
  NativeDirectoryWatchSubscription,
  NativeDeletionCancellationMode,
  NativeDeletionFailure,
  NativeDeletionOperationSnapshot,
  NativeDeletionOperationType,
  NativeDeletionSuccess,
  NativeFileBreadcrumb,
  NativeFileKind,
  NativeFileConflictStrategy,
  NativeFileMetadata,
  NativeFileMutation,
  NativeFileOperationFailure,
  NativeFileOperationSnapshot,
  NativeFileOperationState,
  NativeFileOperationSuccess,
  NativeFileOperationType,
  NativeFileAttributes,
  NativeFileProperties,
  NativeFilePropertyItem,
  NativeFilePreviewDescriptor,
  NativeFilePreviewDiagnostics,
  NativeFilePreviewKind,
  NativeFilePreviewMode,
  NativeFilePreviewRequest,
  NativeFilePreviewSnapshot,
  NativeFilePreviewState,
  NativeFileRoot,
  NativeFileRootKind,
  NativePropertyItemKind,
  NativeVolumeProperties,
  NativeFileRoots,
  NativeFileSearchDiagnostics,
  NativeFileSearchKind,
  NativeFileSearchQuery,
  NativeFileSearchScope,
  NativeFileSearchSnapshot,
  NativeFileSearchState,
  NativeFilesystemEventKind,
  NativeFilesystemWatchEvent,
  PickedFiles,
  PickedPlatformFile,
  PickFilesOptions,
  PlatformCapabilities,
  PlatformFileFilter,
  PlatformFilesystem,
  PlatformNotification,
  PlatformNotificationPermission,
  PlatformRuntime,
  PlatformServiceInfo,
  PlatformServices,
  PlatformWebSurfaces,
  SavedFile,
  SaveFileOptions,
  WebSurfaceBounds,
  WebSurfaceControl,
  WebSurfaceOwner,
  WebSurfaceOpenRequest,
  WebSurfaceSnapshot,
} from './contracts';
